version: '3.2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.0.1
    environment:
    - discovery.type=single-node
    - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    - xpack.graph.enabled=true
    - xpack.security.enabled=false
    ports:
    - 9300:9300
    - 9200:9200
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://elastic:9200
      interval: 5s
      timeout: 120s
      retries: 5
    volumes:
    - es_data:/usr/share/elasticsearch/data:rw

  cerebro:
    image: yannart/cerebro:0.6.6
    ports:
    - 9000:9000
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://cerebro:9000
      interval: 5s
      timeout: 60s
      retries: 5
      
  nifi:
    image: apache/nifi:1.4.0
    ports:
    - 8080:8080
    - 8181:8181
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://nifi:8080
      interval: 5s
      timeout: 60s
      retries: 5
    volumes:
    - nifi_data:/nifi_data

  kibana:
    image: docker.elastic.co/kibana/kibana-x-pack:6.0.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elastic:9200
    ports:
    - 5601:5601
    depends_on:
    - elastic
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://kibana:5601
      interval: 5s
      timeout: 60s
      retries: 5

volumes:
    es_data:
    nifi_data:
